name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  native-experiments:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        experiment-project: [ cloud-function-app, cloud-loadbalancer-app, kofu, reactive-feign-app ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        gu-binary: [ gu, gu.cmd ]
        exclude:
          - os: ubuntu-latest
            gu-binary: gu.cmd
          - os: macos-latest
            gu-binary: gu.cmd
          - os: windows-latest
            gu-binary: gu
    steps:
      - uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.3.0'
          java: 'java17'
      - name: Install native-image component
        run: |
          ${{ matrix.gu-binary }} install native-image
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :${{ matrix.experiment-project }}:nativeBuild
